import { EpicPatientCase, OperatingRoom, BoardRunner, User, FlowState, EmrApiConfig } from '@/types/flow';

export const initialUsers: User[] = [
  { id: 'u1', username: 'runner', displayName: 'Board Runner (Alaniz, P / Veronica N)', role: 'board_runner', pin: '1234' },
  { id: 'u2', username: 'anes', displayName: 'Dr. Alaniz, P (Anesthesiologist)', role: 'anesthesia', pin: '2468' },
  { id: 'u3', username: 'chargern', displayName: 'Veronica N. (Charge RN)', role: 'charge_rn', pin: '5555' },
  { id: 'u4', username: 'circulator', displayName: 'Marybeth Q. (Circulating RN)', role: 'circulator', pin: '1111' },
  { id: 'u5', username: 'admin', displayName: 'OR Director (Superuser)', role: 'superuser', pin: '9999' },
  { id: 'u6', username: 'guest', displayName: 'Clinical Viewer', role: 'basic_viewer', pin: '' }
];

export const initialRooms: OperatingRoom[] = [
  {
    id: 'room-ds-01',
    name: 'MC DS 01',
    department: 'Day Surgery',
    displayOrder: 1,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Jones, E (MD)',
      crna: 'Taylor, K. (CRNA)',
      circulatorRN: 'Holly W. (RN)',
      scrubTech: 'Stephanie (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-ds-02',
    name: 'MC DS 02',
    department: 'Day Surgery',
    displayOrder: 2,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Jones, E (MD)',
      crna: 'Erica B. (CRNA)',
      circulatorRN: 'Kashish M. (RN)',
      scrubTech: 'Candace S. (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-ds-03',
    name: 'MC DS 03',
    department: 'Day Surgery',
    displayOrder: 3,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Prichard, C (MD)',
      crna: 'Marcus J. (CRNA)',
      circulatorRN: 'Arlene S. (RN)',
      scrubTech: 'Nathalie S. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-ds-04',
    name: 'MC DS 04',
    department: 'Day Surgery',
    displayOrder: 4,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Gelpi-Hammond, F (MD)',
      crna: 'Indy B. (CRNA)',
      circulatorRN: 'Jennifer W. (RN)',
      scrubTech: 'David L. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-ds-05',
    name: 'MC DS 05',
    department: 'Day Surgery',
    displayOrder: 5,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Chen, D (MD)',
      crna: 'Indy B. (CRNA)',
      circulatorRN: 'Marybeth Q. (RN)',
      scrubTech: 'Kenji M. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-01',
    name: 'MC OR 01',
    department: 'Main OR',
    displayOrder: 1,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Perez, R (MD)',
      crna: 'Marcus J. (CRNA)',
      circulatorRN: 'Jennifer W. (RN)',
      scrubTech: 'David L. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-02',
    name: 'MC OR 02',
    department: 'Main OR',
    displayOrder: 2,
    status: 'turnover',
    cleaningStatus: 'cleaning',
    assignedStaff: {
      anesthesiologist: 'Alaniz, P (MD)',
      crna: 'Erica B. (CRNA)',
      circulatorRN: 'Holly W. (RN)',
      scrubTech: 'Stephanie (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-03',
    name: 'MC OR 03',
    department: 'Main OR',
    displayOrder: 3,
    status: 'hold',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Alaniz, P (MD)',
      crna: 'Taylor, K. (CRNA)',
      circulatorRN: 'Kashish M. (RN)',
      scrubTech: 'Candace S. (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-04',
    name: 'MC OR 04',
    department: 'Main OR',
    displayOrder: 4,
    status: 'idle',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Alaniz, P (MD)',
      crna: 'Vargas, M. (CRNA)',
      circulatorRN: 'Arlene S. (RN)',
      scrubTech: 'Nathalie S. (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-05',
    name: 'MC OR 05',
    department: 'Main OR',
    displayOrder: 5,
    status: 'closing',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Chen, D (MD)',
      crna: 'Indy B. (CRNA)',
      circulatorRN: 'Sarah T. (RN)',
      scrubTech: 'Kenji M. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-06',
    name: 'MC OR 06',
    department: 'Main OR',
    displayOrder: 6,
    status: 'in_case',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Alaniz, P (MD)',
      crna: 'Erica B. (CRNA)',
      circulatorRN: 'Marybeth Q. (RN)',
      scrubTech: 'Rakesha R. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-07',
    name: 'MC OR 07',
    department: 'Main OR',
    displayOrder: 7,
    status: 'idle',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Chen, D (MD)',
      crna: 'Indy B. (CRNA)',
      circulatorRN: 'Beth R. (RN)',
      scrubTech: 'Jackson T. (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-08',
    name: 'MC OR 08',
    department: 'Main OR',
    displayOrder: 8,
    status: 'idle',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Alaniz, P (MD)',
      crna: 'Taylor, K. (CRNA)',
      circulatorRN: 'Rachel P. (RN)',
      scrubTech: 'David L. (ST)',
      anesTech: 'Sam R.'
    }
  },
  {
    id: 'room-ort-06',
    name: 'MC ORT OR 06',
    department: 'Ortho OR',
    displayOrder: 9,
    status: 'turnover',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Perez, R (MD)',
      crna: 'Marcus J. (CRNA)',
      circulatorRN: 'Beth R. (RN)',
      scrubTech: 'Jackson T. (ST)',
      anesTech: 'Carlos G.'
    }
  },
  {
    id: 'room-endo',
    name: 'Endo Suite 1',
    department: 'Endo',
    displayOrder: 10,
    status: 'idle',
    cleaningStatus: 'clean',
    assignedStaff: {
      anesthesiologist: 'Chen, D (MD)',
      crna: 'Indy B. (CRNA)',
      circulatorRN: 'Yenis S. (RN)',
      scrubTech: 'Kenji M. (ST)',
      anesTech: 'Sam R.'
    }
  }
];

export const initialRunners: BoardRunner[] = [
  { id: 'r1', title: 'Board Runners', staffName: 'Alaniz, P (MD) / Veronica N (RN)', pagerOrPhone: 'Anes x3346 | RN x3935', role: 'anes' },
  { id: 'r2', title: 'WP Board Runners', staffName: 'Chen, D (MD) / Sarah M (RN)', pagerOrPhone: 'Anes x4342', role: 'wp' },
  { id: 'r3', title: 'WP GEN FLOAT', staffName: 'Taylor, K. (CRNA)', pagerOrPhone: 'x8821', role: 'float' },
  { id: 'r4', title: '1ST LATE', staffName: 'Marybeth Q. (RN)', pagerOrPhone: 'x4102', role: 'late' },
  { id: 'r5', title: '2ND LATE', staffName: 'Indy B. (CRNA)', pagerOrPhone: 'x4105', role: 'late' },
  { id: 'r6', title: '3RD LATE', staffName: 'Marcus J. (RN)', pagerOrPhone: 'x4110', role: 'late' },
  { id: 'r7', title: '4TH LATE', staffName: 'Yenis S. (RN)', pagerOrPhone: 'x4118', role: 'late' },
  { id: 'r8', title: 'CV FLOAT ❤', staffName: 'CV Service Team', pagerOrPhone: 'x9900', role: 'float' },
  { id: 'r9', title: 'ORT Board Runners', staffName: 'Gualtieri, A (MD) / Beth R (RN)', pagerOrPhone: 'x5501', role: 'wp' },
  { id: 'r10', title: 'ORT 1ST LATE', staffName: 'Jackson, T. (RN)', pagerOrPhone: 'x5510', role: 'late' },
  { id: 'r11', title: 'ORT 2ND LATE', staffName: 'Miller, D. (CRNA)', pagerOrPhone: 'x5512', role: 'late' }
];

export const initialEmrConfig: EmrApiConfig = {
  provider: 'epic_optime',
  endpointUrl: 'https://epic-gateway.hospital.org/interconnect-fhir/v1/optime',
  clientId: 'perfect-flow-epic-client-7734',
  clientSecretMasked: '••••••••••••••••••••••••3a9b',
  facilityCode: 'MHMC (Memorial Hermann Medical Center)',
  status: 'connected',
  lastPingTime: '18:25:00',
  syncIntervalSec: 30,
  autoSyncEnabled: true,
  minTurnoverBufferMinutes: 15
};

export const initialPatients: EpicPatientCase[] = [
  // === DAY SURGERY CASES (EXACT MATCH TO HOSPITAL CONSOLIDATED STACKED SCREENSHOT) ===
  // Room: MC DS 01
  {
    id: 'pt-ds01-1',
    epicCaseId: '966869',
    mrn: '966869',
    accountNumber: '10198149101',
    patientName: 'Jan, Fabian',
    patientInitials: 'JAN,F',
    age: 1,
    gender: 'M',
    dob: '2025-02-10',
    heightCm: 72,
    weightKg: 9.2,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 01',
    caseOrder: '1',
    primaryProcedure: 'CIRCUMCISION',
    procedureCodes: ['54150'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Taylor, K.',
    circulatorRN: 'Holly W.',
    scrubTech: 'Stephanie',
    currentPhase: 'in_surgery',
    scheduledArrival: '06:00',
    schedInRoom: '07:00',
    schedCut: '07:15',
    schedOutRoom: '08:30',
    scheduledStartTime: '07:00',
    scheduledEndTime: '08:30',
    inRoomTime: '07:02',
    surgeryStartTime: '07:18',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds01-2',
    epicCaseId: '943215',
    mrn: '943215',
    accountNumber: '10198149102',
    patientName: 'Tejeda, Aaron',
    patientInitials: 'TEJ,A',
    age: 1,
    gender: 'M',
    dob: '2025-01-20',
    heightCm: 74,
    weightKg: 9.8,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 01',
    caseOrder: '2',
    primaryProcedure: 'CIRCUMCISION',
    procedureCodes: ['54150'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Taylor, K.',
    circulatorRN: 'Holly W.',
    scrubTech: 'Stephanie',
    currentPhase: 'preop',
    scheduledArrival: '07:30',
    schedInRoom: '09:00',
    schedCut: '09:15',
    schedOutRoom: '10:30',
    scheduledStartTime: '09:00',
    scheduledEndTime: '10:30',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'pending',
    surgicalConsent: 'pending',
    anesthesiaConsent: 'pending',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    preOpAlerts: 'Need H&P; Need Surgical Consent; Need Anesthesia Consent'
  },
  {
    id: 'pt-ds01-3',
    epicCaseId: '955113',
    mrn: '955113',
    accountNumber: '10198149103',
    patientName: 'Al, Maya',
    patientInitials: 'AL ,M',
    age: 2,
    gender: 'F',
    dob: '2024-10-14',
    heightCm: 84,
    weightKg: 12.1,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 01',
    caseOrder: '3',
    primaryProcedure: 'CIRCUMCISION REVISION',
    procedureCodes: ['54163'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Taylor, K.',
    circulatorRN: 'Holly W.',
    scrubTech: 'Stephanie',
    currentPhase: 'scheduled',
    scheduledArrival: '09:30',
    schedInRoom: '11:00',
    schedCut: '11:15',
    schedOutRoom: '12:30',
    scheduledStartTime: '11:00',
    scheduledEndTime: '12:30',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'pending',
    surgicalConsent: 'pending',
    anesthesiaConsent: 'pending',
    siteMarked: 'pending',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    preOpAlerts: 'Need H&P; Need Surgical Consent; Need Anesthesia Consent'
  },

  // Room: MC DS 02
  {
    id: 'pt-ds02-1',
    epicCaseId: '954223',
    mrn: '954223',
    accountNumber: '10198149104',
    patientName: 'Jackson, Aiden',
    patientInitials: 'JAC,A',
    age: 1,
    gender: 'M',
    dob: '2025-01-28',
    heightCm: 71,
    weightKg: 9.4,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 02',
    caseOrder: '1',
    primaryProcedure: 'CORRECTION PENILE CHORDEE, CORRECTION PENILE TORSION, CIRCUMCISION, ROTATIONAL SKIN FLAPS',
    procedureCodes: ['54300', '54161'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Erica B.',
    circulatorRN: 'Kashish M.',
    scrubTech: 'Candace S.',
    currentPhase: 'in_surgery',
    scheduledArrival: '06:30',
    schedInRoom: '08:00',
    schedCut: '08:20',
    schedOutRoom: '09:45',
    scheduledStartTime: '08:00',
    scheduledEndTime: '09:45',
    inRoomTime: '08:05',
    surgeryStartTime: '08:25',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'pending',
    surgicalConsent: 'pending',
    anesthesiaConsent: 'pending',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    preOpAlerts: 'Need H&P; Need Surgical Consent; Need Anesthesia Consent'
  },
  {
    id: 'pt-ds02-2',
    epicCaseId: '954925',
    mrn: '954925',
    accountNumber: '10198149105',
    patientName: 'McGregor, Kevin',
    patientInitials: 'MCG,K',
    age: 1,
    gender: 'M',
    dob: '2024-11-20',
    heightCm: 76,
    weightKg: 10.5,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 02',
    caseOrder: '2',
    primaryProcedure: 'CORRECTION PENILE CHORDEE, CORRECTION PENILE TORSION, CIRCUMCISION',
    procedureCodes: ['54300', '54150'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Erica B.',
    circulatorRN: 'Kashish M.',
    scrubTech: 'Candace S.',
    currentPhase: 'scheduled',
    scheduledArrival: '08:30',
    schedInRoom: '10:00',
    schedCut: '10:20',
    schedOutRoom: '11:45',
    scheduledStartTime: '10:00',
    scheduledEndTime: '11:45',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds02-3',
    epicCaseId: '982467',
    mrn: '982467',
    accountNumber: '10198149106',
    patientName: 'Lopez, Ian',
    patientInitials: 'LOP,I',
    age: 3,
    gender: 'M',
    dob: '2022-12-15',
    heightCm: 98,
    weightKg: 15.6,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 02',
    caseOrder: '3',
    primaryProcedure: 'CIRCUMCISION, CHORDEE RELEASE',
    procedureCodes: ['54161', '54300'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Jones, E.',
    anesthesiologist: 'Jones, E',
    crna: 'Erica B.',
    circulatorRN: 'Kashish M.',
    scrubTech: 'Candace S.',
    currentPhase: 'scheduled',
    scheduledArrival: '10:30',
    schedInRoom: '12:00',
    schedCut: '12:15',
    schedOutRoom: '13:30',
    scheduledStartTime: '12:00',
    scheduledEndTime: '13:30',
    comments: 'NAME ALERT;',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'pending',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // Room: MC DS 03
  {
    id: 'pt-ds03-1',
    epicCaseId: '1000840',
    mrn: '1000840',
    accountNumber: '10198149107',
    patientName: 'Ramirez, Robert',
    patientInitials: 'RAM,R',
    age: 54,
    gender: 'M',
    dob: '1972-04-12',
    heightCm: 178,
    weightKg: 86,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 03',
    caseOrder: '1',
    primaryProcedure: 'THYROIDECTOMY, SUBSTERNAL THYROID, CERVICAL APPROACH',
    procedureCodes: ['60240', '60271'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Prichard, C.',
    anesthesiologist: 'Prichard, C',
    crna: 'Marcus J.',
    circulatorRN: 'Arlene S.',
    scrubTech: 'Nathalie S.',
    currentPhase: 'in_surgery',
    scheduledArrival: '05:45',
    schedInRoom: '07:00',
    schedCut: '07:30',
    schedOutRoom: '09:30',
    scheduledStartTime: '07:00',
    scheduledEndTime: '09:30',
    inRoomTime: '07:05',
    surgeryStartTime: '07:32',
    comments: '2 assistants',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds03-2',
    epicCaseId: '988194',
    mrn: '988194',
    accountNumber: '10198149108',
    patientName: 'Strauss, Joan',
    patientInitials: 'STR,J',
    age: 74,
    gender: 'F',
    dob: '1952-08-19',
    heightCm: 162,
    weightKg: 68,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 03',
    caseOrder: '2',
    primaryProcedure: 'LEFT BREAST COMPLETE AXILLARY LYMPH NODE DISSECTION, LEFT BREAST SAVI EXCISION NODE X2',
    procedureCodes: ['38745', '19125'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Lee, T.',
    anesthesiologist: 'Prichard, C',
    crna: 'Marcus J.',
    circulatorRN: 'Arlene S.',
    scrubTech: 'Nathalie S.',
    currentPhase: 'preop',
    scheduledArrival: '08:15',
    schedInRoom: '10:00',
    schedCut: '10:30',
    schedOutRoom: '11:45',
    scheduledStartTime: '10:00',
    scheduledEndTime: '11:45',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'completed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds03-3',
    epicCaseId: '993777',
    mrn: '993777',
    accountNumber: '10198149109',
    patientName: 'Brooks, Teresa',
    patientInitials: 'BRO,T',
    age: 48,
    gender: 'F',
    dob: '1978-03-04',
    heightCm: 167,
    weightKg: 73,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 03',
    caseOrder: '3',
    primaryProcedure: 'HYSTEROSCOPIC POLYPECTOMY, DILATION AND CURETTAGE, ANY OTHER INDICATED PROCEDURES',
    procedureCodes: ['58558', '58120'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Ekwo, T.',
    anesthesiologist: 'Prichard, C',
    crna: 'Marcus J.',
    circulatorRN: 'Arlene S.',
    scrubTech: 'Nathalie S.',
    currentPhase: 'scheduled',
    scheduledArrival: '10:30',
    schedInRoom: '12:00',
    schedCut: '12:30',
    schedOutRoom: '13:45',
    scheduledStartTime: '12:00',
    scheduledEndTime: '13:45',
    comments: 'Myosure, REP WILL BE PRESENT FOR CASE',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'na',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // Room: MC DS 04
  {
    id: 'pt-ds04-1',
    epicCaseId: '938712',
    mrn: '938712',
    accountNumber: '10198149110',
    patientName: 'Pineda, Rosa',
    patientInitials: 'PIN,R',
    age: 77,
    gender: 'F',
    dob: '1949-11-05',
    heightCm: 157,
    weightKg: 64,
    inpatientBed: 'IP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 04',
    caseOrder: '1',
    primaryProcedure: 'LUMBAR DISCECTOMY AND DECOMPRESSION',
    procedureCodes: ['63030'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Gelpi-Hammond, F.',
    anesthesiologist: 'Gelpi-Hammond, F',
    crna: 'Indy B.',
    circulatorRN: 'Jennifer W.',
    scrubTech: 'David L.',
    currentPhase: 'in_surgery',
    scheduledArrival: '06:30',
    schedInRoom: '08:00',
    schedCut: '08:30',
    schedOutRoom: '09:15',
    scheduledStartTime: '08:00',
    scheduledEndTime: '09:15',
    inRoomTime: '08:02',
    surgeryStartTime: '08:28',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds04-2',
    epicCaseId: '1001147',
    mrn: '1001147',
    accountNumber: '10198149111',
    patientName: 'Taub, Edward',
    patientInitials: 'TAU,E',
    age: 92,
    gender: 'M',
    dob: '1934-06-25',
    heightCm: 170,
    weightKg: 70,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 04',
    caseOrder: '2',
    primaryProcedure: 'CERVICAL FORAMINOTOMY',
    procedureCodes: ['63045'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Gelpi-Hammond, F.',
    anesthesiologist: 'Gelpi-Hammond, F',
    crna: 'Indy B.',
    circulatorRN: 'Jennifer W.',
    scrubTech: 'David L.',
    currentPhase: 'scheduled',
    scheduledArrival: '08:00',
    schedInRoom: '09:30',
    schedCut: '10:00',
    schedOutRoom: '11:30',
    scheduledStartTime: '09:30',
    scheduledEndTime: '11:30',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds04-3',
    epicCaseId: '977778',
    mrn: '977778',
    accountNumber: '10198149112',
    patientName: 'Wiesner, Margaret',
    patientInitials: 'WIE,M',
    age: 66,
    gender: 'F',
    dob: '1960-01-14',
    heightCm: 165,
    weightKg: 78,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 04',
    caseOrder: '3',
    primaryProcedure: 'LAPAROSCOPIC CHOLECYSTECTOMY',
    procedureCodes: ['47562'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Soni, S.',
    anesthesiologist: 'Gelpi-Hammond, F',
    crna: 'Indy B.',
    circulatorRN: 'Jennifer W.',
    scrubTech: 'David L.',
    currentPhase: 'scheduled',
    scheduledArrival: '10:30',
    schedInRoom: '12:00',
    schedCut: '12:30',
    schedOutRoom: '13:45',
    scheduledStartTime: '12:00',
    scheduledEndTime: '13:45',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // Room: MC DS 05
  {
    id: 'pt-ds05-1',
    epicCaseId: '1014822',
    mrn: '1014822',
    accountNumber: '10198149113',
    patientName: 'Kiil, Elena',
    patientInitials: 'KII,E',
    age: 44,
    gender: 'F',
    dob: '1982-09-08',
    heightCm: 168,
    weightKg: 66,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 05',
    caseOrder: '1',
    primaryProcedure: 'TOTAL ABDOMINAL HYSTERECTOMY, BILATERAL SALPINGO-OOPHORECTOMY',
    procedureCodes: ['58150'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Faro, J.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    circulatorRN: 'Marybeth Q.',
    scrubTech: 'Kenji M.',
    currentPhase: 'in_surgery',
    scheduledArrival: '05:45',
    schedInRoom: '07:00',
    schedCut: '07:30',
    schedOutRoom: '08:45',
    scheduledStartTime: '07:00',
    scheduledEndTime: '08:45',
    inRoomTime: '07:04',
    surgeryStartTime: '07:30',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds05-2',
    epicCaseId: '1011402',
    mrn: '1011402',
    accountNumber: '10198149114',
    patientName: 'Ray, Rebecca',
    patientInitials: 'RAY,R',
    age: 58,
    gender: 'F',
    dob: '1968-07-22',
    heightCm: 160,
    weightKg: 69,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 05',
    caseOrder: '1',
    primaryProcedure: 'LEFT BREAST MODIFIED RADICAL MASTECTOMY',
    procedureCodes: ['19307'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Lee, T.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    circulatorRN: 'Marybeth Q.',
    scrubTech: 'Kenji M.',
    currentPhase: 'scheduled',
    scheduledArrival: '07:30',
    schedInRoom: '09:00',
    schedCut: '09:30',
    schedOutRoom: '10:45',
    scheduledStartTime: '09:00',
    scheduledEndTime: '10:45',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds05-3',
    epicCaseId: '1011646',
    mrn: '1011646',
    accountNumber: '10198149115',
    patientName: 'Vance, Susan',
    patientInitials: 'VAN,S',
    age: 48,
    gender: 'F',
    dob: '1978-02-17',
    heightCm: 172,
    weightKg: 75,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 05',
    caseOrder: '3',
    primaryProcedure: 'SENTINEL LYMPH NODE BIOPSY',
    procedureCodes: ['38500'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Lee, T.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    circulatorRN: 'Marybeth Q.',
    scrubTech: 'Kenji M.',
    currentPhase: 'scheduled',
    scheduledArrival: '09:30',
    schedInRoom: '11:00',
    schedCut: '11:30',
    schedOutRoom: '12:30',
    scheduledStartTime: '11:00',
    scheduledEndTime: '12:30',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },
  {
    id: 'pt-ds05-4',
    epicCaseId: '986015',
    mrn: '986015',
    accountNumber: '10198149116',
    patientName: 'Washington, Carl',
    patientInitials: 'WAS,C',
    age: 56,
    gender: 'M',
    dob: '1970-05-11',
    heightCm: 180,
    weightKg: 89,
    inpatientBed: 'OP Surg',
    isConfidential: false,
    roomNumber: 'MC DS 05',
    caseOrder: '4',
    primaryProcedure: 'URETEROSCOPY WITH LASER LITHOTRIPSY',
    procedureCodes: ['52356'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Siller, B., Seizman, A.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    circulatorRN: 'Marybeth Q.',
    scrubTech: 'Kenji M.',
    currentPhase: 'scheduled',
    scheduledArrival: '11:30',
    schedInRoom: '13:00',
    schedCut: '13:30',
    schedOutRoom: '14:45',
    scheduledStartTime: '13:00',
    scheduledEndTime: '14:45',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: false,
    anesthesiaTechReady: false,
    blockStatus: 'not_needed',
    reportCalled: false,
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // === MAIN OR CASES ===
  // 1. MC OR 06: Active Case 3 (Jose Ernesto Perez - exact replica of image)
  {
    id: 'pt-1015987',
    epicCaseId: '1015987',
    mrn: '151159090',
    accountNumber: '10198149392',
    patientName: 'Perez, Jose Ernesto',
    patientInitials: 'PER, J',
    age: 56,
    gender: 'M',
    dob: '1970-06-11',
    heightCm: 165.1,
    weightKg: 61.6,
    inpatientBed: 'MH8.836',
    isConfidential: false,
    roomNumber: 'MC OR 06',
    caseOrder: 'B-3',
    primaryProcedure: 'LEFT HALLUX AMPUTATION, INCISION & DRAINAGE, APPLICATION OF ANTIBIOTIC BEADS',
    secondaryProcedure: 'INCISION AND DRAINAGE, FOOT',
    procedureCodes: ['1071001197', '1071001175'],
    casePriority: 'urgent',
    isAddOn: true,
    addOnTime: '20:09',
    addedBy: 'Night Charge RN',
    anesthesiaType: 'General',
    comments: 'TF URO CASE',
    surgeon: 'Lee, K',
    anesthesiologist: 'Alaniz, P',
    crna: 'Erica B.',
    circulatorRN: 'Marybeth Q.',
    scrubTech: 'Rakesha R.',
    preOpRN: 'Yenis S.',
    currentPhase: 'in_surgery',
    scheduledArrival: '09:30',

    // Exact times from OR Control screenshot:
    // Sched: In-Room 10:55 | Cut 10:55 | Out-Room 12:55
    schedInRoom: '10:55',
    schedCut: '10:55',
    schedOutRoom: '12:55',
    scheduledStartTime: '10:55',
    scheduledEndTime: '12:55',

    // Act/Upd: In-Room 11:15 | Cut 11:30 | Surgery End 11:55 | Out-Room 12:00
    inRoomTime: '11:15',
    surgeryStartTime: '11:30', // Cut
    surgeryEndTime: '11:55',   // Surgery End
    outRoomTime: undefined,    // active in room

    preOpReady: true,
    preOpReadyTime: '11:09',
    surgeonSeen: true,
    surgeonSeenTime: '10:48',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaReadyTime: '11:05',
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: true,
    reportCalledTime: '11:10',
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    familyCommunication: {
      primaryName: 'Elena Perez (Spouse)',
      primaryPhone: '(713) 555-0192',
      primaryNotes: 'In Surgical Waiting Area B, prefers text and phone update when out of room',
      prefersPhoneCall: true
    }
  },

  // 2. MC OR 05: Closing Case 1 (Arthur Gonzalez / Quentin Williams)
  {
    id: 'pt-1015072',
    epicCaseId: '1015072',
    mrn: '151152011',
    accountNumber: '10198149201',
    patientName: 'Williams, Quentin',
    patientInitials: 'WIL, Q',
    age: 45,
    gender: 'M',
    dob: '1981-03-14',
    heightCm: 178.0,
    weightKg: 84.0,
    inpatientBed: 'E5.526',
    isConfidential: false,
    roomNumber: 'MC OR 05',
    caseOrder: '1',
    primaryProcedure: 'CHOLECYSTECTOMY, LAPAROSCOPIC WITH INDOCYANINE GREEN AND INTRAOPERATIVE CHOLANGIOGRAM',
    secondaryProcedure: 'WITH IOC AND ICG, NO ASSISTANT',
    procedureCodes: ['47563', '1015072'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Gonzalez, A.',
    surgicalAssistant: 'Schmidt, K.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    circulatorRN: 'Sarah T.',
    scrubTech: 'Kenji M.',
    currentPhase: 'closing',
    scheduledArrival: '06:30',
    schedInRoom: '08:00',
    schedCut: '08:15',
    schedOutRoom: '10:15',
    scheduledStartTime: '08:00',
    scheduledEndTime: '10:15',
    inRoomTime: '08:21',
    surgeryStartTime: '08:45',
    surgeryEndTime: '10:05',
    preOpReady: true,
    preOpReadyTime: '07:45',
    surgeonSeen: true,
    surgeonSeenTime: '07:50',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: true,
    reportCalledTime: '08:15',
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // 3. MC OR 05: Queued Case 2 (Linda Cortez - in Pre-Op Bay 02)
  // Scheduled In-Room: 10:45 (30-min buffer after Case 1 ends at 10:15, safely > 15m buffer)
  {
    id: 'pt-1015503',
    epicCaseId: '1015503',
    mrn: '151154890',
    accountNumber: '10198149255',
    patientName: 'Cortez, Linda',
    patientInitials: 'COR, L',
    age: 66,
    gender: 'F',
    dob: '1960-08-22',
    heightCm: 162.0,
    weightKg: 72.5,
    inpatientBed: 'E5.511',
    isConfidential: false,
    roomNumber: 'MC OR 05',
    caseOrder: '2',
    primaryProcedure: 'CHOLECYSTECTOMY, LAPAROSCOPIC, WITH CHOLANGIOGRAM AND ICG',
    procedureCodes: ['47563', '1015503'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Gonzalez, A.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    preOpRN: 'Yenis S.',
    preOpBay: 'Bay 02',
    currentPhase: 'preop',
    scheduledArrival: '09:00',
    schedInRoom: '10:45',
    schedCut: '11:00',
    schedOutRoom: '12:30',
    scheduledStartTime: '10:45',
    scheduledEndTime: '12:30',
    preOpReady: true,
    preOpReadyTime: '10:10',
    surgeonSeen: true,
    surgeonSeenTime: '10:15',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaReadyTime: '10:20',
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: true,
    reportCalledTime: '10:25',
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    familyCommunication: {
      primaryName: 'Robert Cortez (Son)',
      primaryPhone: '(713) 555-8831',
      prefersPhoneCall: true
    }
  },

  // 4. MC OR 01: Active Case 1 (Eleanor Vance - Total Knee)
  {
    id: 'pt-1016204',
    epicCaseId: '1016204',
    mrn: '151158810',
    accountNumber: '10198149411',
    patientName: 'Vance, Eleanor',
    patientInitials: 'VAN, E',
    age: 68,
    gender: 'F',
    dob: '1957-11-04',
    heightCm: 158.0,
    weightKg: 69.0,
    inpatientBed: 'MH7.712',
    isConfidential: false,
    roomNumber: 'MC OR 01',
    caseOrder: '1',
    primaryProcedure: 'ROBOTIC TOTAL KNEE ARTHROPLASTY, LEFT',
    secondaryProcedure: 'WITH COMPUTER-AIDED NAVIGATION AND EXTENSOR MECHANISM BALANCING',
    procedureCodes: ['27447', 'S2900'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'Spinal',
    surgeon: 'Gualtieri, A.',
    surgicalAssistant: 'Taylor, B.',
    anesthesiologist: 'Perez, R',
    crna: 'Marcus J.',
    circulatorRN: 'Jennifer W.',
    scrubTech: 'David L.',
    preOpRN: 'David C.',
    currentPhase: 'in_surgery',
    scheduledArrival: '07:00',
    schedInRoom: '08:30',
    schedCut: '09:00',
    schedOutRoom: '11:30',
    scheduledStartTime: '08:30',
    scheduledEndTime: '11:30',
    inRoomTime: '09:10',
    surgeryStartTime: '09:35', // Cut
    preOpReady: true,
    preOpReadyTime: '08:45',
    surgeonSeen: true,
    surgeonSeenTime: '08:50',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaReadyTime: '09:00',
    anesthesiaTechReady: true,
    blockStatus: 'completed',
    blockType: 'Adductor Canal + iPACK Block',
    reportCalled: true,
    reportCalledTime: '09:05',
    uptResult: 'na',
    clipNeeded: 'yes_done',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: true,
    ptOrdered: true,
    familyCommunication: {
      primaryName: 'Thomas Vance (Husband)',
      primaryPhone: '(832) 555-7721',
      prefersPhoneCall: true
    }
  },

  // 5. MC OR 02: Room Turnover / Queued Case 2 (Marcus Brody - in Pre-Op Bay 04)
  {
    id: 'pt-1015891',
    epicCaseId: '1015891',
    mrn: '151156644',
    accountNumber: '10198149302',
    patientName: 'Brody, Marcus',
    patientInitials: 'BRO, M',
    age: 52,
    gender: 'M',
    dob: '1974-05-19',
    heightCm: 182.0,
    weightKg: 90.5,
    inpatientBed: 'Outpatient Ambulatory',
    isConfidential: false,
    roomNumber: 'MC OR 02',
    caseOrder: '2',
    primaryProcedure: 'UMBILICAL HERNIA REPAIR WITH MESH, ROBOTIC-ASSISTED',
    procedureCodes: ['49585', '49593'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Lee, K',
    anesthesiologist: 'Alaniz, P',
    crna: 'Erica B.',
    preOpRN: 'Yenis S.',
    preOpBay: 'Bay 04',
    currentPhase: 'preop',
    scheduledArrival: '09:30',
    schedInRoom: '11:15',
    schedCut: '11:45',
    schedOutRoom: '13:00',
    scheduledStartTime: '11:15',
    scheduledEndTime: '13:00',
    preOpReady: true,
    preOpReadyTime: '10:30',
    surgeonSeen: true,
    surgeonSeenTime: '10:40',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaReadyTime: '10:45',
    anesthesiaTechReady: true,
    blockStatus: 'completed',
    blockType: 'Bilateral TAP Block',
    reportCalled: true,
    reportCalledTime: '10:50',
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: false,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // 6. Pre-Op Bay 01: Delay Alert (David Kim - Pending Surgeon Site Marking)
  {
    id: 'pt-1016330',
    epicCaseId: '1016330',
    mrn: '151159902',
    accountNumber: '10198149501',
    patientName: 'Kim, David',
    patientInitials: 'KIM, D',
    age: 41,
    gender: 'M',
    dob: '1985-09-30',
    heightCm: 175.0,
    weightKg: 78.0,
    inpatientBed: 'Outpatient Ambulatory',
    isConfidential: false,
    roomNumber: 'MC OR 03',
    caseOrder: '1',
    primaryProcedure: 'ARTHROSCOPIC ROTATOR CUFF REPAIR, RIGHT SHOULDER WITH ACROMIOPLASTY',
    procedureCodes: ['29827', '29826'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Hastings, W',
    anesthesiologist: 'Alaniz, P',
    preOpRN: 'Yenis S.',
    preOpBay: 'Bay 01',
    currentPhase: 'preop',
    scheduledArrival: '10:00',
    schedInRoom: '11:30',
    schedCut: '12:00',
    schedOutRoom: '13:45',
    scheduledStartTime: '11:30',
    scheduledEndTime: '13:45',
    delayReason: 'Awaiting Surgeon arrival for mandatory surgical site mark and updated H&P',
    preOpReady: false,
    surgeonSeen: false,
    hpComplete: 'pending',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'pending',
    anesthesiaReady: true,
    anesthesiaReadyTime: '10:35',
    anesthesiaTechReady: true,
    blockStatus: 'ordered',
    blockType: 'Interscalene Brachial Plexus Block',
    reportCalled: false,
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: false,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    preOpAlerts: 'SURGEON NOT ARRIVED - SITE UNMARKED',
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // 7. Pre-Op Bay 03: Regional Block Procedure Underway (Maria Santos)
  {
    id: 'pt-1016412',
    epicCaseId: '1016412',
    mrn: '151160120',
    accountNumber: '10198149588',
    patientName: 'Santos, Maria',
    patientInitials: 'SAN, M',
    age: 33,
    gender: 'F',
    dob: '1992-12-15',
    heightCm: 164.0,
    weightKg: 63.0,
    inpatientBed: 'Outpatient Ambulatory',
    isConfidential: false,
    roomNumber: 'MC OR 04',
    caseOrder: '2',
    primaryProcedure: 'OPEN REDUCTION AND INTERNAL FIXATION (ORIF) BIMALLEOLAR ANKLE FRACTURE, RIGHT',
    procedureCodes: ['27814', '20680'],
    casePriority: 'urgent',
    isAddOn: false,
    anesthesiaType: 'Regional',
    surgeon: 'Lee, K',
    anesthesiologist: 'Alaniz, P',
    crna: 'Taylor, K.',
    preOpRN: 'David C.',
    preOpBay: 'Bay 03',
    currentPhase: 'preop',
    scheduledArrival: '10:30',
    schedInRoom: '12:00',
    schedCut: '12:30',
    schedOutRoom: '14:30',
    scheduledStartTime: '12:00',
    scheduledEndTime: '14:30',
    preOpReady: true,
    preOpReadyTime: '11:00',
    surgeonSeen: true,
    surgeonSeenTime: '10:45',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaReadyTime: '11:00',
    anesthesiaTechReady: true,
    blockStatus: 'in_progress',
    blockType: 'Popliteal Sciatic + Adductor Canal Saphenous Nerve Block',
    reportCalled: false,
    uptResult: 'negative',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: false,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: true,
    ptOrdered: false
  },

  // 8. Pre-Op Bay 05: Urgent Add-On Case (Robert Sterling)
  {
    id: 'pt-1016789',
    epicCaseId: '1016789',
    mrn: '151161405',
    accountNumber: '10198149722',
    patientName: 'Sterling, Robert',
    patientInitials: 'STE, R',
    age: 72,
    gender: 'M',
    dob: '1954-02-08',
    heightCm: 171.0,
    weightKg: 82.0,
    inpatientBed: 'MH6.602',
    isConfidential: false,
    roomNumber: 'MC OR 07',
    caseOrder: 'Add-On',
    primaryProcedure: 'EXPLORATORY LAPAROTOMY, SMALL BOWEL RESECTION WITH PRIMARY ANASTOMOSIS',
    procedureCodes: ['44120', '49000'],
    casePriority: 'urgent',
    isAddOn: true,
    addOnTime: '10:45',
    addedBy: 'Dr. Adams (Trauma / Acute Care Surgery)',
    anesthesiaType: 'General',
    comments: 'URGENT BOWEL OBSTRUCTION - ADD-ON CASE',
    surgeon: 'Adams, T.',
    anesthesiologist: 'Chen, D',
    crna: 'Indy B.',
    preOpRN: 'Yenis S.',
    preOpBay: 'Bay 05',
    currentPhase: 'preop',
    scheduledArrival: '10:45',
    schedInRoom: '12:15',
    schedCut: '12:45',
    schedOutRoom: '15:00',
    scheduledStartTime: '12:15',
    scheduledEndTime: '15:00',
    preOpReady: true,
    preOpReadyTime: '11:15',
    surgeonSeen: true,
    surgeonSeenTime: '11:00',
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'na',
    anesthesiaReady: true,
    anesthesiaReadyTime: '11:20',
    anesthesiaTechReady: true,
    blockStatus: 'not_needed',
    reportCalled: true,
    reportCalledTime: '11:22',
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: true,
    medicationSpecial: '2 units PRBC on standby in blood bank',
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: true,
    anesthesiaTransport: true,
    specialNeeds: 'Pacemaker interrogator requested on standby',
    preOpBypass: false,
    erasPathway: false,
    scopeEgd: false,
    pacuTransportComplete: false,
    readyForAnesSignout: false,
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false
  },

  // 9. PACU Bay 03: Recovering / Floor Hold (Samantha Jenkins)
  {
    id: 'pt-1016032',
    epicCaseId: '1016032',
    mrn: '151157920',
    accountNumber: '10198149350',
    patientName: 'Jenkins, Samantha',
    patientInitials: 'JEN, S',
    age: 64,
    gender: 'F',
    dob: '1962-04-20',
    heightCm: 167.0,
    weightKg: 76.2,
    inpatientBed: 'MH8.834',
    isConfidential: false,
    roomNumber: 'MC ORT OR 06',
    caseOrder: '1',
    primaryProcedure: 'RIGHT HIP TOTAL ARTHROPLASTY REVISION WITH HEAD AND LINER EXCHANGE',
    secondaryProcedure: 'IRRIGATION AND EXTENSIVE DEBRIDEMENT',
    procedureCodes: ['27134', '1016032'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'Spinal',
    surgeon: 'Gualtieri, A.',
    anesthesiologist: 'Perez, R',
    pacuRN: 'Bethany K.',
    pacuLocation: 'PACU Bay 03',
    currentPhase: 'pacu',
    scheduledArrival: '06:45',
    schedInRoom: '08:00',
    schedCut: '08:30',
    schedOutRoom: '10:15',
    scheduledStartTime: '08:00',
    scheduledEndTime: '10:15',
    inRoomTime: '08:05',
    surgeryStartTime: '08:30',
    surgeryEndTime: '10:05',
    outRoomTime: '10:20',
    pacuArrivalTime: '10:25',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'completed',
    reportCalled: true,
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: true,
    readyForAnesSignout: true,
    anesSignoutTime: '11:05',
    pacuToFloorHold: true,
    xrayOrdered: true,
    ptOrdered: true,
    recoveryNeeds: 'Inpatient Bed Hold: Floor MH8 bed clean pending. Vital signs stable, Aldrete score 9/10.',
    familyCommunication: {
      primaryName: 'Mark Jenkins (Husband)',
      primaryPhone: '(281) 555-4921',
      prefersPhoneCall: true
    }
  },

  // 10. Phase II Station 02: Outpatient Ready for Discharge (Carlos Mendez)
  {
    id: 'pt-1016555',
    epicCaseId: '1016555',
    mrn: '151160882',
    accountNumber: '10198149610',
    patientName: 'Mendez, Carlos',
    patientInitials: 'MEN, C',
    age: 29,
    gender: 'M',
    dob: '1997-07-07',
    heightCm: 180.0,
    weightKg: 85.0,
    inpatientBed: 'Ambulatory Phase II',
    isConfidential: false,
    roomNumber: 'MC OR 08',
    caseOrder: '1',
    primaryProcedure: 'LEFT KNEE ARTHROSCOPY, PARTIAL MEDIAL MENISCECTOMY',
    procedureCodes: ['29881'],
    casePriority: 'elective',
    isAddOn: false,
    anesthesiaType: 'General',
    surgeon: 'Hastings, W',
    anesthesiologist: 'Alaniz, P',
    phase2Nurse: 'Rachel P.',
    phase2Location: 'Phase II Station 02',
    currentPhase: 'phase2',
    scheduledArrival: '07:30',
    schedInRoom: '09:00',
    schedCut: '09:20',
    schedOutRoom: '10:15',
    scheduledStartTime: '09:00',
    scheduledEndTime: '10:15',
    inRoomTime: '09:05',
    surgeryStartTime: '09:20',
    surgeryEndTime: '10:05',
    outRoomTime: '10:15',
    pacuArrivalTime: '10:20',
    phase2ArrivalTime: '11:00',
    preOpReady: true,
    surgeonSeen: true,
    hpComplete: 'yes',
    surgicalConsent: 'signed',
    anesthesiaConsent: 'signed',
    siteMarked: 'yes',
    anesthesiaReady: true,
    anesthesiaTechReady: true,
    blockStatus: 'completed',
    blockType: 'Femoral Nerve Block',
    reportCalled: true,
    uptResult: 'na',
    clipNeeded: 'no',
    circPreopVisit: true,
    roomReady: true,
    bloodBankRequired: false,
    latexAllergy: false,
    infectionStatus: 'none',
    defibPacemaker: false,
    anesthesiaTransport: false,
    preOpBypass: false,
    erasPathway: true,
    scopeEgd: false,
    pacuTransportComplete: true,
    readyForAnesSignout: true,
    anesSignoutTime: '10:55',
    pacuToFloorHold: false,
    xrayOrdered: false,
    ptOrdered: false,
    recoveryNeeds: 'Tolerating oral fluids, ambulating with crutches, prescriptions filled. Ride home confirmed (Spouse in discharge lobby).',
    familyCommunication: {
      primaryName: 'Sofia Mendez (Spouse)',
      primaryPhone: '(713) 555-3349',
      prefersPhoneCall: false
    }
  }
];

export function getInitialFlowState(): FlowState {
  return {
    version: '1.0.0',
    lastUpdated: new Date().toISOString(),
    patients: initialPatients,
    rooms: initialRooms,
    runners: initialRunners,
    users: initialUsers,
    emrConfig: initialEmrConfig,
    auditLogs: [
      {
        id: 'log-1',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        user: 'Night Charge RN',
        action: 'ADD_ON_CREATED',
        patientId: 'pt-1015987',
        patientName: 'Perez, Jose Ernesto',
        details: 'Urgent Add-On case booked for MC OR 06 (Hallux amputation)'
      },
      {
        id: 'log-2',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        user: 'Alaniz, P (MD)',
        action: 'PREOP_ANESTHESIA_READY',
        patientId: 'pt-1015503',
        patientName: 'Cortez, Linda',
        details: 'Anesthesia pre-op complete & cleared for OR 05'
      }
    ]
  };
}
